server:
  port: 8096

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/assignment_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.king.boot.bootdemo.entity

student:
  name: jingyiWang
  age: 2
